---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    name: "mydeployment"
  name: "mydeployment"
spec:
  replicas: 5
  selector:
    matchLabels:
      server: "nginx"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        server: "nginx"
    spec:
      containers:
      - image: "nginx:latest"
        name: "nginxcontainer"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"