---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    name: "myPod"
  name: "nginx"
spec:
  containers:
  - image: "nginx:latest"
    name: "nginxcontainer"
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"